# Generated by Django 4.2 on 2023-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="price_after_discount",
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
        ),
    ]
