# Generated by Django 4.2 on 2023-09-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productinfo_price_after_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinfo",
            name="price_after_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
