# Generated by Django 4.2 on 2023-09-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productinfo_price_after_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratingreview",
            name="product_img",
            field=models.ImageField(blank=True, null=True, upload_to="ReviewProduct"),
        ),
    ]
